// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAdminToken = `-- name: CreateAdminToken :one
INSERT INTO admin_tokens (
  id,
  org_id,
  name,
  token_prefix,
  token_hash,
  scopes,
  status,
  expires_at,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, org_id, name, token_prefix, token_hash, scopes, status, expires_at, last_used_at, created_at, revoked_at
`

type CreateAdminTokenParams struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	OrgID       uuid.UUID  `db:"org_id" json:"org_id"`
	Name        string     `db:"name" json:"name"`
	TokenPrefix string     `db:"token_prefix" json:"token_prefix"`
	TokenHash   string     `db:"token_hash" json:"token_hash"`
	Scopes      []string   `db:"scopes" json:"scopes"`
	Status      string     `db:"status" json:"status"`
	ExpiresAt   *time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAdminToken(ctx context.Context, arg CreateAdminTokenParams) (AdminToken, error) {
	row := q.db.QueryRow(ctx, createAdminToken,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Scopes,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i AdminToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scopes,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminToken = `-- name: GetAdminToken :one
SELECT id, org_id, name, token_prefix, token_hash, scopes, status, expires_at, last_used_at, created_at, revoked_at
FROM admin_tokens
WHERE org_id = $1 AND id = $2
`

type GetAdminTokenParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAdminToken(ctx context.Context, arg GetAdminTokenParams) (AdminToken, error) {
	row := q.db.QueryRow(ctx, getAdminToken, arg.OrgID, arg.ID)
	var i AdminToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scopes,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminTokenByHash = `-- name: GetAdminTokenByHash :one
SELECT id, org_id, name, token_prefix, token_hash, scopes, status, expires_at, last_used_at, created_at, revoked_at
FROM admin_tokens
WHERE token_hash = $1
`

func (q *Queries) GetAdminTokenByHash(ctx context.Context, tokenHash string) (AdminToken, error) {
	row := q.db.QueryRow(ctx, getAdminTokenByHash, tokenHash)
	var i AdminToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scopes,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAdminTokens = `-- name: ListAdminTokens :many
SELECT id, org_id, name, token_prefix, token_hash, scopes, status, expires_at, last_used_at, created_at, revoked_at
FROM admin_tokens
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAdminTokens(ctx context.Context, orgID uuid.UUID) ([]AdminToken, error) {
	rows, err := q.db.Query(ctx, listAdminTokens, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminToken{}
	for rows.Next() {
		var i AdminToken
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.TokenPrefix,
			&i.TokenHash,
			&i.Scopes,
			&i.Status,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminToken = `-- name: RevokeAdminToken :one
UPDATE admin_tokens
SET status = 'revoked',
    revoked_at = $3
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, token_prefix, token_hash, scopes, status, expires_at, last_used_at, created_at, revoked_at
`

type RevokeAdminTokenParams struct {
	OrgID     uuid.UUID  `db:"org_id" json:"org_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
	RevokedAt *time.Time `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeAdminToken(ctx context.Context, arg RevokeAdminTokenParams) (AdminToken, error) {
	row := q.db.QueryRow(ctx, revokeAdminToken, arg.OrgID, arg.ID, arg.RevokedAt)
	var i AdminToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Scopes,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAdminTokenLastUsed = `-- name: TouchAdminTokenLastUsed :exec
UPDATE admin_tokens
SET last_used_at = $3
WHERE org_id = $1 AND id = $2
`

type TouchAdminTokenLastUsedParams struct {
	OrgID      uuid.UUID  `db:"org_id" json:"org_id"`
	ID         uuid.UUID  `db:"id" json:"id"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) TouchAdminTokenLastUsed(ctx context.Context, arg TouchAdminTokenLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAdminTokenLastUsed, arg.OrgID, arg.ID, arg.LastUsedAt)
	return err
}
