// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_logs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :one
INSERT INTO admin_audit_logs (
  id,
  org_id,
  actor_admin_token_id,
  action,
  resource_type,
  resource_id,
  request_id,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, actor_admin_token_id, action, resource_type, resource_id, request_id, created_at
`

type InsertAdminAuditLogParams struct {
	ID                uuid.UUID  `db:"id" json:"id"`
	OrgID             uuid.UUID  `db:"org_id" json:"org_id"`
	ActorAdminTokenID uuid.UUID  `db:"actor_admin_token_id" json:"actor_admin_token_id"`
	Action            string     `db:"action" json:"action"`
	ResourceType      string     `db:"resource_type" json:"resource_type"`
	ResourceID        *uuid.UUID `db:"resource_id" json:"resource_id"`
	RequestID         string     `db:"request_id" json:"request_id"`
	CreatedAt         time.Time  `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAdminAuditLog,
		arg.ID,
		arg.OrgID,
		arg.ActorAdminTokenID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.RequestID,
		arg.CreatedAt,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorAdminTokenID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT id, org_id, actor_admin_token_id, action, resource_type, resource_id, request_id, created_at
FROM admin_audit_logs
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAdminAuditLogsParams struct {
	OrgID  uuid.UUID `db:"org_id" json:"org_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLogs, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAuditLog{}
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorAdminTokenID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
