// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
  id,
  org_id,
  name,
  key_prefix,
  key_hash,
  scopes,
  status,
  rpm_limit,
  expires_at,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, org_id, name, key_prefix, key_hash, scopes, status, rpm_limit, expires_at, last_used_at, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	OrgID     uuid.UUID  `db:"org_id" json:"org_id"`
	Name      string     `db:"name" json:"name"`
	KeyPrefix string     `db:"key_prefix" json:"key_prefix"`
	KeyHash   string     `db:"key_hash" json:"key_hash"`
	Scopes    []string   `db:"scopes" json:"scopes"`
	Status    string     `db:"status" json:"status"`
	RpmLimit  int32      `db:"rpm_limit" json:"rpm_limit"`
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.Status,
		arg.RpmLimit,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.RpmLimit,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, org_id, name, key_prefix, key_hash, scopes, status, rpm_limit, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE org_id = $1 AND id = $2
`

type GetAPIKeyParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.OrgID, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.RpmLimit,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, org_id, name, key_prefix, key_hash, scopes, status, rpm_limit, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.RpmLimit,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, org_id, name, key_prefix, key_hash, scopes, status, rpm_limit, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, orgID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Status,
			&i.RpmLimit,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET status = 'revoked',
    revoked_at = $3
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, key_prefix, key_hash, scopes, status, rpm_limit, expires_at, last_used_at, created_at, revoked_at
`

type RevokeAPIKeyParams struct {
	OrgID     uuid.UUID  `db:"org_id" json:"org_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
	RevokedAt *time.Time `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.OrgID, arg.ID, arg.RevokedAt)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.RpmLimit,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $3
WHERE org_id = $1 AND id = $2
`

type TouchAPIKeyLastUsedParams struct {
	OrgID      uuid.UUID  `db:"org_id" json:"org_id"`
	ID         uuid.UUID  `db:"id" json:"id"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.OrgID, arg.ID, arg.LastUsedAt)
	return err
}
