// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (
  id,
  org_id,
  name,
  scope_type,
  scope_id,
  period,
  limit_micro_usd,
  action,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, org_id, name, scope_type, scope_id, period, limit_micro_usd, action, status, created_at, updated_at
`

type CreateBudgetParams struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	OrgID         uuid.UUID  `db:"org_id" json:"org_id"`
	Name          string     `db:"name" json:"name"`
	ScopeType     string     `db:"scope_type" json:"scope_type"`
	ScopeID       *uuid.UUID `db:"scope_id" json:"scope_id"`
	Period        string     `db:"period" json:"period"`
	LimitMicroUsd int64      `db:"limit_micro_usd" json:"limit_micro_usd"`
	Action        string     `db:"action" json:"action"`
	Status        string     `db:"status" json:"status"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time  `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.ScopeType,
		arg.ScopeID,
		arg.Period,
		arg.LimitMicroUsd,
		arg.Action,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitMicroUsd,
		&i.Action,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudget = `-- name: GetBudget :one
SELECT id, org_id, name, scope_type, scope_id, period, limit_micro_usd, action, status, created_at, updated_at
FROM budgets
WHERE org_id = $1 AND id = $2
`

type GetBudgetParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.OrgID, arg.ID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.ScopeType,
		&i.ScopeID,
		&i.Period,
		&i.LimitMicroUsd,
		&i.Action,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetUsedAmount = `-- name: GetBudgetUsedAmount :one
SELECT COALESCE(SUM(total_cost_micro), 0)::bigint AS used_micro_usd
FROM cost_records
WHERE org_id = $1
  AND created_at >= $2
  AND created_at < $3
`

type GetBudgetUsedAmountParams struct {
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
}

func (q *Queries) GetBudgetUsedAmount(ctx context.Context, arg GetBudgetUsedAmountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBudgetUsedAmount, arg.OrgID, arg.CreatedAt, arg.CreatedAt_2)
	var used_micro_usd int64
	err := row.Scan(&used_micro_usd)
	return used_micro_usd, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, org_id, name, scope_type, scope_id, period, limit_micro_usd, action, status, created_at, updated_at
FROM budgets
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBudgets(ctx context.Context, orgID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.ScopeType,
			&i.ScopeID,
			&i.Period,
			&i.LimitMicroUsd,
			&i.Action,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
