// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budget_alerts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBudgetAlert = `-- name: CreateBudgetAlert :one
INSERT INTO budget_alerts (
  id,
  org_id,
  budget_id,
  webhook_url,
  webhook_secret,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, budget_id, webhook_url, webhook_secret, status, created_at, updated_at
`

type CreateBudgetAlertParams struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	OrgID         uuid.UUID   `db:"org_id" json:"org_id"`
	BudgetID      uuid.UUID   `db:"budget_id" json:"budget_id"`
	WebhookUrl    string      `db:"webhook_url" json:"webhook_url"`
	WebhookSecret pgtype.Text `db:"webhook_secret" json:"webhook_secret"`
	Status        string      `db:"status" json:"status"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateBudgetAlert(ctx context.Context, arg CreateBudgetAlertParams) (BudgetAlert, error) {
	row := q.db.QueryRow(ctx, createBudgetAlert,
		arg.ID,
		arg.OrgID,
		arg.BudgetID,
		arg.WebhookUrl,
		arg.WebhookSecret,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BudgetAlert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BudgetID,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetAlert = `-- name: GetBudgetAlert :one
SELECT id, org_id, budget_id, webhook_url, webhook_secret, status, created_at, updated_at
FROM budget_alerts
WHERE org_id = $1 AND id = $2
`

type GetBudgetAlertParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetBudgetAlert(ctx context.Context, arg GetBudgetAlertParams) (BudgetAlert, error) {
	row := q.db.QueryRow(ctx, getBudgetAlert, arg.OrgID, arg.ID)
	var i BudgetAlert
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BudgetID,
		&i.WebhookUrl,
		&i.WebhookSecret,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBudgetAlertDelivery = `-- name: InsertBudgetAlertDelivery :one
INSERT INTO budget_alert_deliveries (
  id,
  org_id,
  budget_alert_id,
  budget_id,
  threshold,
  period,
  period_window_start,
  period_window_end,
  used_micro_usd,
  limit_micro_usd,
  webhook_url,
  status,
  http_status,
  error_message,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, org_id, budget_alert_id, budget_id, threshold, period, period_window_start, period_window_end, used_micro_usd, limit_micro_usd, webhook_url, status, http_status, error_message, created_at
`

type InsertBudgetAlertDeliveryParams struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	OrgID             uuid.UUID   `db:"org_id" json:"org_id"`
	BudgetAlertID     uuid.UUID   `db:"budget_alert_id" json:"budget_alert_id"`
	BudgetID          uuid.UUID   `db:"budget_id" json:"budget_id"`
	Threshold         int32       `db:"threshold" json:"threshold"`
	Period            string      `db:"period" json:"period"`
	PeriodWindowStart time.Time   `db:"period_window_start" json:"period_window_start"`
	PeriodWindowEnd   time.Time   `db:"period_window_end" json:"period_window_end"`
	UsedMicroUsd      int64       `db:"used_micro_usd" json:"used_micro_usd"`
	LimitMicroUsd     int64       `db:"limit_micro_usd" json:"limit_micro_usd"`
	WebhookUrl        string      `db:"webhook_url" json:"webhook_url"`
	Status            string      `db:"status" json:"status"`
	HttpStatus        pgtype.Int4 `db:"http_status" json:"http_status"`
	ErrorMessage      pgtype.Text `db:"error_message" json:"error_message"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertBudgetAlertDelivery(ctx context.Context, arg InsertBudgetAlertDeliveryParams) (BudgetAlertDelivery, error) {
	row := q.db.QueryRow(ctx, insertBudgetAlertDelivery,
		arg.ID,
		arg.OrgID,
		arg.BudgetAlertID,
		arg.BudgetID,
		arg.Threshold,
		arg.Period,
		arg.PeriodWindowStart,
		arg.PeriodWindowEnd,
		arg.UsedMicroUsd,
		arg.LimitMicroUsd,
		arg.WebhookUrl,
		arg.Status,
		arg.HttpStatus,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	var i BudgetAlertDelivery
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BudgetAlertID,
		&i.BudgetID,
		&i.Threshold,
		&i.Period,
		&i.PeriodWindowStart,
		&i.PeriodWindowEnd,
		&i.UsedMicroUsd,
		&i.LimitMicroUsd,
		&i.WebhookUrl,
		&i.Status,
		&i.HttpStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveBudgetAlerts = `-- name: ListActiveBudgetAlerts :many
SELECT id, org_id, budget_id, webhook_url, webhook_secret, status, created_at, updated_at
FROM budget_alerts
WHERE org_id = $1 AND status = 'active'
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListActiveBudgetAlerts(ctx context.Context, orgID uuid.UUID) ([]BudgetAlert, error) {
	rows, err := q.db.Query(ctx, listActiveBudgetAlerts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetAlert{}
	for rows.Next() {
		var i BudgetAlert
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BudgetID,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetAlertDeliveries = `-- name: ListBudgetAlertDeliveries :many
SELECT id, org_id, budget_alert_id, budget_id, threshold, period, period_window_start, period_window_end, used_micro_usd, limit_micro_usd, webhook_url, status, http_status, error_message, created_at
FROM budget_alert_deliveries
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListBudgetAlertDeliveriesParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	Limit int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListBudgetAlertDeliveries(ctx context.Context, arg ListBudgetAlertDeliveriesParams) ([]BudgetAlertDelivery, error) {
	rows, err := q.db.Query(ctx, listBudgetAlertDeliveries, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetAlertDelivery{}
	for rows.Next() {
		var i BudgetAlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BudgetAlertID,
			&i.BudgetID,
			&i.Threshold,
			&i.Period,
			&i.PeriodWindowStart,
			&i.PeriodWindowEnd,
			&i.UsedMicroUsd,
			&i.LimitMicroUsd,
			&i.WebhookUrl,
			&i.Status,
			&i.HttpStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetAlertDeliveriesByBudgetWindow = `-- name: ListBudgetAlertDeliveriesByBudgetWindow :many
SELECT id, org_id, budget_alert_id, budget_id, threshold, period, period_window_start, period_window_end, used_micro_usd, limit_micro_usd, webhook_url, status, http_status, error_message, created_at
FROM budget_alert_deliveries
WHERE org_id = $1
  AND budget_id = $2
  AND period_window_start = $3
ORDER BY threshold ASC
`

type ListBudgetAlertDeliveriesByBudgetWindowParams struct {
	OrgID             uuid.UUID `db:"org_id" json:"org_id"`
	BudgetID          uuid.UUID `db:"budget_id" json:"budget_id"`
	PeriodWindowStart time.Time `db:"period_window_start" json:"period_window_start"`
}

func (q *Queries) ListBudgetAlertDeliveriesByBudgetWindow(ctx context.Context, arg ListBudgetAlertDeliveriesByBudgetWindowParams) ([]BudgetAlertDelivery, error) {
	rows, err := q.db.Query(ctx, listBudgetAlertDeliveriesByBudgetWindow, arg.OrgID, arg.BudgetID, arg.PeriodWindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetAlertDelivery{}
	for rows.Next() {
		var i BudgetAlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BudgetAlertID,
			&i.BudgetID,
			&i.Threshold,
			&i.Period,
			&i.PeriodWindowStart,
			&i.PeriodWindowEnd,
			&i.UsedMicroUsd,
			&i.LimitMicroUsd,
			&i.WebhookUrl,
			&i.Status,
			&i.HttpStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetAlerts = `-- name: ListBudgetAlerts :many
SELECT id, org_id, budget_id, webhook_url, webhook_secret, status, created_at, updated_at
FROM budget_alerts
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListBudgetAlerts(ctx context.Context, orgID uuid.UUID) ([]BudgetAlert, error) {
	rows, err := q.db.Query(ctx, listBudgetAlerts, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetAlert{}
	for rows.Next() {
		var i BudgetAlert
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BudgetID,
			&i.WebhookUrl,
			&i.WebhookSecret,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
