// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache_events.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertCacheEvent = `-- name: InsertCacheEvent :one
INSERT INTO cache_events (
  id,
  org_id,
  request_log_id,
  event_type,
  requested_model,
  cache_key_hash,
  messages_hash,
  reason,
  metadata,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, org_id, request_log_id, event_type, requested_model, cache_key_hash, messages_hash, reason, metadata, created_at
`

type InsertCacheEventParams struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	OrgID          uuid.UUID        `db:"org_id" json:"org_id"`
	RequestLogID   *uuid.UUID       `db:"request_log_id" json:"request_log_id"`
	EventType      string           `db:"event_type" json:"event_type"`
	RequestedModel string           `db:"requested_model" json:"requested_model"`
	CacheKeyHash   string           `db:"cache_key_hash" json:"cache_key_hash"`
	MessagesHash   string           `db:"messages_hash" json:"messages_hash"`
	Reason         pgtype.Text      `db:"reason" json:"reason"`
	Metadata       *json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt      time.Time        `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertCacheEvent(ctx context.Context, arg InsertCacheEventParams) (CacheEvent, error) {
	row := q.db.QueryRow(ctx, insertCacheEvent,
		arg.ID,
		arg.OrgID,
		arg.RequestLogID,
		arg.EventType,
		arg.RequestedModel,
		arg.CacheKeyHash,
		arg.MessagesHash,
		arg.Reason,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i CacheEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RequestLogID,
		&i.EventType,
		&i.RequestedModel,
		&i.CacheKeyHash,
		&i.MessagesHash,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listCacheEvents = `-- name: ListCacheEvents :many
SELECT id, org_id, request_log_id, event_type, requested_model, cache_key_hash, messages_hash, reason, metadata, created_at
FROM cache_events
WHERE org_id = $1
  AND created_at >= $2
  AND created_at < $3
  AND ($4::text IS NULL OR event_type = $4::text)
  AND ($5::text IS NULL OR requested_model = $5::text)
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListCacheEventsParams struct {
	OrgID          uuid.UUID   `db:"org_id" json:"org_id"`
	FromAt         time.Time   `db:"from_at" json:"from_at"`
	ToAt           time.Time   `db:"to_at" json:"to_at"`
	EventType      pgtype.Text `db:"event_type" json:"event_type"`
	RequestedModel pgtype.Text `db:"requested_model" json:"requested_model"`
	Limit          int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListCacheEvents(ctx context.Context, arg ListCacheEventsParams) ([]CacheEvent, error) {
	rows, err := q.db.Query(ctx, listCacheEvents,
		arg.OrgID,
		arg.FromAt,
		arg.ToAt,
		arg.EventType,
		arg.RequestedModel,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CacheEvent{}
	for rows.Next() {
		var i CacheEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RequestLogID,
			&i.EventType,
			&i.RequestedModel,
			&i.CacheKeyHash,
			&i.MessagesHash,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
