// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_policies.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createContentPolicy = `-- name: CreateContentPolicy :one
INSERT INTO content_policies (
  id,
  org_id,
  name,
  pii_action,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, org_id, name, pii_action, status, created_at, updated_at
`

type CreateContentPolicyParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	OrgID     uuid.UUID `db:"org_id" json:"org_id"`
	Name      string    `db:"name" json:"name"`
	PiiAction string    `db:"pii_action" json:"pii_action"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateContentPolicy(ctx context.Context, arg CreateContentPolicyParams) (ContentPolicy, error) {
	row := q.db.QueryRow(ctx, createContentPolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.PiiAction,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ContentPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.PiiAction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveContentPolicy = `-- name: GetActiveContentPolicy :one
SELECT id, org_id, name, pii_action, status, created_at, updated_at
FROM content_policies
WHERE org_id = $1
  AND status = 'active'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetActiveContentPolicy(ctx context.Context, orgID uuid.UUID) (ContentPolicy, error) {
	row := q.db.QueryRow(ctx, getActiveContentPolicy, orgID)
	var i ContentPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.PiiAction,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentPolicies = `-- name: ListContentPolicies :many
SELECT id, org_id, name, pii_action, status, created_at, updated_at
FROM content_policies
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListContentPolicies(ctx context.Context, orgID uuid.UUID) ([]ContentPolicy, error) {
	rows, err := q.db.Query(ctx, listContentPolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentPolicy{}
	for rows.Next() {
		var i ContentPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.PiiAction,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
