// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cost_anomaly_policies.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCostAnomalyPolicy = `-- name: CreateCostAnomalyPolicy :one
INSERT INTO cost_anomaly_policies (
  id,
  org_id,
  name,
  rule_type,
  scope_type,
  scope_id,
  model_alias,
  threshold_micro_usd,
  threshold_bps,
  spike_multiplier_bps,
  current_window_minutes,
  baseline_window_minutes,
  min_requests,
  action,
  fallback_model,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, org_id, name, rule_type, scope_type, scope_id, model_alias, threshold_micro_usd, threshold_bps, spike_multiplier_bps, current_window_minutes, baseline_window_minutes, min_requests, action, fallback_model, status, created_at, updated_at
`

type CreateCostAnomalyPolicyParams struct {
	ID                    uuid.UUID   `db:"id" json:"id"`
	OrgID                 uuid.UUID   `db:"org_id" json:"org_id"`
	Name                  string      `db:"name" json:"name"`
	RuleType              string      `db:"rule_type" json:"rule_type"`
	ScopeType             string      `db:"scope_type" json:"scope_type"`
	ScopeID               *uuid.UUID  `db:"scope_id" json:"scope_id"`
	ModelAlias            pgtype.Text `db:"model_alias" json:"model_alias"`
	ThresholdMicroUsd     pgtype.Int8 `db:"threshold_micro_usd" json:"threshold_micro_usd"`
	ThresholdBps          pgtype.Int4 `db:"threshold_bps" json:"threshold_bps"`
	SpikeMultiplierBps    int32       `db:"spike_multiplier_bps" json:"spike_multiplier_bps"`
	CurrentWindowMinutes  int32       `db:"current_window_minutes" json:"current_window_minutes"`
	BaselineWindowMinutes int32       `db:"baseline_window_minutes" json:"baseline_window_minutes"`
	MinRequests           int32       `db:"min_requests" json:"min_requests"`
	Action                string      `db:"action" json:"action"`
	FallbackModel         pgtype.Text `db:"fallback_model" json:"fallback_model"`
	Status                string      `db:"status" json:"status"`
	CreatedAt             time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCostAnomalyPolicy(ctx context.Context, arg CreateCostAnomalyPolicyParams) (CostAnomalyPolicy, error) {
	row := q.db.QueryRow(ctx, createCostAnomalyPolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.RuleType,
		arg.ScopeType,
		arg.ScopeID,
		arg.ModelAlias,
		arg.ThresholdMicroUsd,
		arg.ThresholdBps,
		arg.SpikeMultiplierBps,
		arg.CurrentWindowMinutes,
		arg.BaselineWindowMinutes,
		arg.MinRequests,
		arg.Action,
		arg.FallbackModel,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CostAnomalyPolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.RuleType,
		&i.ScopeType,
		&i.ScopeID,
		&i.ModelAlias,
		&i.ThresholdMicroUsd,
		&i.ThresholdBps,
		&i.SpikeMultiplierBps,
		&i.CurrentWindowMinutes,
		&i.BaselineWindowMinutes,
		&i.MinRequests,
		&i.Action,
		&i.FallbackModel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCostAnomalyPolicies = `-- name: ListActiveCostAnomalyPolicies :many
SELECT id, org_id, name, rule_type, scope_type, scope_id, model_alias, threshold_micro_usd, threshold_bps, spike_multiplier_bps, current_window_minutes, baseline_window_minutes, min_requests, action, fallback_model, status, created_at, updated_at
FROM cost_anomaly_policies
WHERE org_id = $1 AND status = 'active'
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListActiveCostAnomalyPolicies(ctx context.Context, orgID uuid.UUID) ([]CostAnomalyPolicy, error) {
	rows, err := q.db.Query(ctx, listActiveCostAnomalyPolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostAnomalyPolicy{}
	for rows.Next() {
		var i CostAnomalyPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.RuleType,
			&i.ScopeType,
			&i.ScopeID,
			&i.ModelAlias,
			&i.ThresholdMicroUsd,
			&i.ThresholdBps,
			&i.SpikeMultiplierBps,
			&i.CurrentWindowMinutes,
			&i.BaselineWindowMinutes,
			&i.MinRequests,
			&i.Action,
			&i.FallbackModel,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostAnomalyPolicies = `-- name: ListCostAnomalyPolicies :many
SELECT id, org_id, name, rule_type, scope_type, scope_id, model_alias, threshold_micro_usd, threshold_bps, spike_multiplier_bps, current_window_minutes, baseline_window_minutes, min_requests, action, fallback_model, status, created_at, updated_at
FROM cost_anomaly_policies
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListCostAnomalyPolicies(ctx context.Context, orgID uuid.UUID) ([]CostAnomalyPolicy, error) {
	rows, err := q.db.Query(ctx, listCostAnomalyPolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostAnomalyPolicy{}
	for rows.Next() {
		var i CostAnomalyPolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.RuleType,
			&i.ScopeType,
			&i.ScopeID,
			&i.ModelAlias,
			&i.ThresholdMicroUsd,
			&i.ThresholdBps,
			&i.SpikeMultiplierBps,
			&i.CurrentWindowMinutes,
			&i.BaselineWindowMinutes,
			&i.MinRequests,
			&i.Action,
			&i.FallbackModel,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
