// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: magic_link_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeMagicLinkToken = `-- name: ConsumeMagicLinkToken :one
UPDATE magic_link_tokens ml
SET status = 'consumed',
    consumed_at = $1::timestamptz
FROM org_memberships m
JOIN users u ON u.id = m.user_id
JOIN organizations o ON o.id = m.org_id
WHERE ml.token_hash = $2::text
  AND ml.org_id = m.org_id
  AND ml.user_id = m.user_id
  AND ml.status = 'active'
  AND ml.consumed_at IS NULL
  AND ml.expires_at > $3::timestamptz
  AND m.status = 'active'
  AND u.status = 'active'
  AND o.status = 'active'
RETURNING
  ml.id,
  ml.org_id,
  o.slug AS org_slug,
  ml.user_id,
  u.email,
  u.display_name,
  m.id AS membership_id,
  m.role,
  ml.expires_at,
  ml.consumed_at
`

type ConsumeMagicLinkTokenParams struct {
	ConsumedAt time.Time `db:"consumed_at" json:"consumed_at"`
	TokenHash  string    `db:"token_hash" json:"token_hash"`
	Now        time.Time `db:"now" json:"now"`
}

type ConsumeMagicLinkTokenRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	OrgID        uuid.UUID  `db:"org_id" json:"org_id"`
	OrgSlug      string     `db:"org_slug" json:"org_slug"`
	UserID       uuid.UUID  `db:"user_id" json:"user_id"`
	Email        string     `db:"email" json:"email"`
	DisplayName  string     `db:"display_name" json:"display_name"`
	MembershipID uuid.UUID  `db:"membership_id" json:"membership_id"`
	Role         string     `db:"role" json:"role"`
	ExpiresAt    time.Time  `db:"expires_at" json:"expires_at"`
	ConsumedAt   *time.Time `db:"consumed_at" json:"consumed_at"`
}

func (q *Queries) ConsumeMagicLinkToken(ctx context.Context, arg ConsumeMagicLinkTokenParams) (ConsumeMagicLinkTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeMagicLinkToken, arg.ConsumedAt, arg.TokenHash, arg.Now)
	var i ConsumeMagicLinkTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.OrgSlug,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.MembershipID,
		&i.Role,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const createMagicLinkToken = `-- name: CreateMagicLinkToken :one
INSERT INTO magic_link_tokens (
  id,
  org_id,
  user_id,
  email,
  token_prefix,
  token_hash,
  status,
  expires_at,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, org_id, user_id, email, token_prefix, token_hash, status, expires_at, consumed_at, created_at
`

type CreateMagicLinkTokenParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Email       string    `db:"email" json:"email"`
	TokenPrefix string    `db:"token_prefix" json:"token_prefix"`
	TokenHash   string    `db:"token_hash" json:"token_hash"`
	Status      string    `db:"status" json:"status"`
	ExpiresAt   time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateMagicLinkToken(ctx context.Context, arg CreateMagicLinkTokenParams) (MagicLinkToken, error) {
	row := q.db.QueryRow(ctx, createMagicLinkToken,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Email,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i MagicLinkToken
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Email,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
