// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID                uuid.UUID  `db:"id" json:"id"`
	OrgID             uuid.UUID  `db:"org_id" json:"org_id"`
	ActorAdminTokenID *uuid.UUID `db:"actor_admin_token_id" json:"actor_admin_token_id"`
	Action            string     `db:"action" json:"action"`
	ResourceType      string     `db:"resource_type" json:"resource_type"`
	ResourceID        *uuid.UUID `db:"resource_id" json:"resource_id"`
	RequestID         string     `db:"request_id" json:"request_id"`
	CreatedAt         time.Time  `db:"created_at" json:"created_at"`
	ActorUserID       *uuid.UUID `db:"actor_user_id" json:"actor_user_id"`
}

type AdminToken struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	OrgID       uuid.UUID  `db:"org_id" json:"org_id"`
	Name        string     `db:"name" json:"name"`
	TokenPrefix string     `db:"token_prefix" json:"token_prefix"`
	TokenHash   string     `db:"token_hash" json:"token_hash"`
	Scopes      []string   `db:"scopes" json:"scopes"`
	Status      string     `db:"status" json:"status"`
	ExpiresAt   *time.Time `db:"expires_at" json:"expires_at"`
	LastUsedAt  *time.Time `db:"last_used_at" json:"last_used_at"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	RevokedAt   *time.Time `db:"revoked_at" json:"revoked_at"`
}

type ApiKey struct {
	ID                       uuid.UUID   `db:"id" json:"id"`
	OrgID                    uuid.UUID   `db:"org_id" json:"org_id"`
	Name                     string      `db:"name" json:"name"`
	KeyPrefix                string      `db:"key_prefix" json:"key_prefix"`
	KeyHash                  string      `db:"key_hash" json:"key_hash"`
	Scopes                   []string    `db:"scopes" json:"scopes"`
	Status                   string      `db:"status" json:"status"`
	RpmLimit                 int32       `db:"rpm_limit" json:"rpm_limit"`
	ExpiresAt                *time.Time  `db:"expires_at" json:"expires_at"`
	LastUsedAt               *time.Time  `db:"last_used_at" json:"last_used_at"`
	CreatedAt                time.Time   `db:"created_at" json:"created_at"`
	RevokedAt                *time.Time  `db:"revoked_at" json:"revoked_at"`
	DailyCostLimitMicroUsd   pgtype.Int8 `db:"daily_cost_limit_micro_usd" json:"daily_cost_limit_micro_usd"`
	MonthlyCostLimitMicroUsd pgtype.Int8 `db:"monthly_cost_limit_micro_usd" json:"monthly_cost_limit_micro_usd"`
	QuotaAction              string      `db:"quota_action" json:"quota_action"`
}

type Budget struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	OrgID         uuid.UUID  `db:"org_id" json:"org_id"`
	Name          string     `db:"name" json:"name"`
	ScopeType     string     `db:"scope_type" json:"scope_type"`
	ScopeID       *uuid.UUID `db:"scope_id" json:"scope_id"`
	Period        string     `db:"period" json:"period"`
	LimitMicroUsd int64      `db:"limit_micro_usd" json:"limit_micro_usd"`
	Action        string     `db:"action" json:"action"`
	Status        string     `db:"status" json:"status"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time  `db:"updated_at" json:"updated_at"`
}

type BudgetAlert struct {
	ID            uuid.UUID   `db:"id" json:"id"`
	OrgID         uuid.UUID   `db:"org_id" json:"org_id"`
	BudgetID      uuid.UUID   `db:"budget_id" json:"budget_id"`
	WebhookUrl    string      `db:"webhook_url" json:"webhook_url"`
	WebhookSecret pgtype.Text `db:"webhook_secret" json:"webhook_secret"`
	Status        string      `db:"status" json:"status"`
	CreatedAt     time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at" json:"updated_at"`
}

type BudgetAlertDelivery struct {
	ID                uuid.UUID   `db:"id" json:"id"`
	OrgID             uuid.UUID   `db:"org_id" json:"org_id"`
	BudgetAlertID     uuid.UUID   `db:"budget_alert_id" json:"budget_alert_id"`
	BudgetID          uuid.UUID   `db:"budget_id" json:"budget_id"`
	Threshold         int32       `db:"threshold" json:"threshold"`
	Period            string      `db:"period" json:"period"`
	PeriodWindowStart time.Time   `db:"period_window_start" json:"period_window_start"`
	PeriodWindowEnd   time.Time   `db:"period_window_end" json:"period_window_end"`
	UsedMicroUsd      int64       `db:"used_micro_usd" json:"used_micro_usd"`
	LimitMicroUsd     int64       `db:"limit_micro_usd" json:"limit_micro_usd"`
	WebhookUrl        string      `db:"webhook_url" json:"webhook_url"`
	Status            string      `db:"status" json:"status"`
	HttpStatus        pgtype.Int4 `db:"http_status" json:"http_status"`
	ErrorMessage      pgtype.Text `db:"error_message" json:"error_message"`
	CreatedAt         time.Time   `db:"created_at" json:"created_at"`
}

type CacheEvent struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	OrgID          uuid.UUID        `db:"org_id" json:"org_id"`
	RequestLogID   *uuid.UUID       `db:"request_log_id" json:"request_log_id"`
	EventType      string           `db:"event_type" json:"event_type"`
	RequestedModel string           `db:"requested_model" json:"requested_model"`
	CacheKeyHash   string           `db:"cache_key_hash" json:"cache_key_hash"`
	MessagesHash   string           `db:"messages_hash" json:"messages_hash"`
	Reason         pgtype.Text      `db:"reason" json:"reason"`
	Metadata       *json.RawMessage `db:"metadata" json:"metadata"`
	CreatedAt      time.Time        `db:"created_at" json:"created_at"`
}

type ContentPolicy struct {
	ID        uuid.UUID `db:"id" json:"id"`
	OrgID     uuid.UUID `db:"org_id" json:"org_id"`
	Name      string    `db:"name" json:"name"`
	PiiAction string    `db:"pii_action" json:"pii_action"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type CostRecord struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	UsageRecordID    uuid.UUID       `db:"usage_record_id" json:"usage_record_id"`
	OrgID            uuid.UUID       `db:"org_id" json:"org_id"`
	ProviderID       uuid.UUID       `db:"provider_id" json:"provider_id"`
	ModelID          uuid.UUID       `db:"model_id" json:"model_id"`
	Currency         string          `db:"currency" json:"currency"`
	InputCostMicro   int64           `db:"input_cost_micro" json:"input_cost_micro"`
	OutputCostMicro  int64           `db:"output_cost_micro" json:"output_cost_micro"`
	TotalCostMicro   int64           `db:"total_cost_micro" json:"total_cost_micro"`
	PricingSnapshot  json.RawMessage `db:"pricing_snapshot" json:"pricing_snapshot"`
	CreatedAt        time.Time       `db:"created_at" json:"created_at"`
	PricingVersionID *uuid.UUID      `db:"pricing_version_id" json:"pricing_version_id"`
}

type Model struct {
	ID                             uuid.UUID   `db:"id" json:"id"`
	OrgID                          uuid.UUID   `db:"org_id" json:"org_id"`
	ProviderID                     uuid.UUID   `db:"provider_id" json:"provider_id"`
	ProviderModelName              string      `db:"provider_model_name" json:"provider_model_name"`
	DisplayName                    string      `db:"display_name" json:"display_name"`
	InputPriceMicroUsdPer1kTokens  int64       `db:"input_price_micro_usd_per_1k_tokens" json:"input_price_micro_usd_per_1k_tokens"`
	OutputPriceMicroUsdPer1kTokens int64       `db:"output_price_micro_usd_per_1k_tokens" json:"output_price_micro_usd_per_1k_tokens"`
	ContextWindow                  pgtype.Int4 `db:"context_window" json:"context_window"`
	Status                         string      `db:"status" json:"status"`
	CreatedAt                      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time   `db:"updated_at" json:"updated_at"`
}

type ModelPricingVersion struct {
	ID                             uuid.UUID  `db:"id" json:"id"`
	OrgID                          uuid.UUID  `db:"org_id" json:"org_id"`
	ModelID                        uuid.UUID  `db:"model_id" json:"model_id"`
	Version                        int32      `db:"version" json:"version"`
	InputPriceMicroUsdPer1kTokens  int64      `db:"input_price_micro_usd_per_1k_tokens" json:"input_price_micro_usd_per_1k_tokens"`
	OutputPriceMicroUsdPer1kTokens int64      `db:"output_price_micro_usd_per_1k_tokens" json:"output_price_micro_usd_per_1k_tokens"`
	Status                         string     `db:"status" json:"status"`
	EffectiveFrom                  time.Time  `db:"effective_from" json:"effective_from"`
	EffectiveTo                    *time.Time `db:"effective_to" json:"effective_to"`
	CreatedAt                      time.Time  `db:"created_at" json:"created_at"`
}

type OrgMembership struct {
	ID        uuid.UUID `db:"id" json:"id"`
	OrgID     uuid.UUID `db:"org_id" json:"org_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Role      string    `db:"role" json:"role"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Name      string    `db:"name" json:"name"`
	Slug      string    `db:"slug" json:"slug"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Provider struct {
	ID                  uuid.UUID   `db:"id" json:"id"`
	OrgID               uuid.UUID   `db:"org_id" json:"org_id"`
	Name                string      `db:"name" json:"name"`
	Type                string      `db:"type" json:"type"`
	BaseUrl             pgtype.Text `db:"base_url" json:"base_url"`
	TimeoutMs           int32       `db:"timeout_ms" json:"timeout_ms"`
	Status              string      `db:"status" json:"status"`
	CreatedAt           time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time   `db:"updated_at" json:"updated_at"`
	LastHealthStatus    pgtype.Text `db:"last_health_status" json:"last_health_status"`
	LastHealthCheckedAt *time.Time  `db:"last_health_checked_at" json:"last_health_checked_at"`
	LastErrorCode       pgtype.Text `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage    pgtype.Text `db:"last_error_message" json:"last_error_message"`
}

type ProviderSecret struct {
	ID              uuid.UUID `db:"id" json:"id"`
	OrgID           uuid.UUID `db:"org_id" json:"org_id"`
	ProviderID      uuid.UUID `db:"provider_id" json:"provider_id"`
	EncryptedApiKey string    `db:"encrypted_api_key" json:"encrypted_api_key"`
	Nonce           string    `db:"nonce" json:"nonce"`
	KeyVersion      int32     `db:"key_version" json:"key_version"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

type RequestLog struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	OrgID             uuid.UUID        `db:"org_id" json:"org_id"`
	ApiKeyID          *uuid.UUID       `db:"api_key_id" json:"api_key_id"`
	ProviderID        *uuid.UUID       `db:"provider_id" json:"provider_id"`
	ModelID           *uuid.UUID       `db:"model_id" json:"model_id"`
	RoutePolicyID     *uuid.UUID       `db:"route_policy_id" json:"route_policy_id"`
	Method            string           `db:"method" json:"method"`
	Path              string           `db:"path" json:"path"`
	RequestModel      pgtype.Text      `db:"request_model" json:"request_model"`
	Status            string           `db:"status" json:"status"`
	StatusCode        int32            `db:"status_code" json:"status_code"`
	ErrorCode         pgtype.Text      `db:"error_code" json:"error_code"`
	RequestHash       pgtype.Text      `db:"request_hash" json:"request_hash"`
	ResponseHash      pgtype.Text      `db:"response_hash" json:"response_hash"`
	LatencyMs         int32            `db:"latency_ms" json:"latency_ms"`
	ProviderLatencyMs pgtype.Int4      `db:"provider_latency_ms" json:"provider_latency_ms"`
	Metadata          *json.RawMessage `db:"metadata" json:"metadata"`
	StartedAt         time.Time        `db:"started_at" json:"started_at"`
	CompletedAt       time.Time        `db:"completed_at" json:"completed_at"`
}

type RoutePolicy struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	OrgID      uuid.UUID       `db:"org_id" json:"org_id"`
	Name       string          `db:"name" json:"name"`
	MatchModel string          `db:"match_model" json:"match_model"`
	Strategy   string          `db:"strategy" json:"strategy"`
	Status     string          `db:"status" json:"status"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time       `db:"updated_at" json:"updated_at"`
	Config     json.RawMessage `db:"config" json:"config"`
}

type RouteTarget struct {
	ID            uuid.UUID `db:"id" json:"id"`
	OrgID         uuid.UUID `db:"org_id" json:"org_id"`
	RoutePolicyID uuid.UUID `db:"route_policy_id" json:"route_policy_id"`
	ProviderID    uuid.UUID `db:"provider_id" json:"provider_id"`
	ModelID       uuid.UUID `db:"model_id" json:"model_id"`
	Priority      int32     `db:"priority" json:"priority"`
	Weight        int32     `db:"weight" json:"weight"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

type UsageRecord struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	RequestLogID      uuid.UUID        `db:"request_log_id" json:"request_log_id"`
	OrgID             uuid.UUID        `db:"org_id" json:"org_id"`
	ApiKeyID          uuid.UUID        `db:"api_key_id" json:"api_key_id"`
	ProviderID        uuid.UUID        `db:"provider_id" json:"provider_id"`
	ModelID           uuid.UUID        `db:"model_id" json:"model_id"`
	PromptTokens      int32            `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens  int32            `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens       int32            `db:"total_tokens" json:"total_tokens"`
	ProviderUsageJson *json.RawMessage `db:"provider_usage_json" json:"provider_usage_json"`
	CreatedAt         time.Time        `db:"created_at" json:"created_at"`
}

type User struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Email       string    `db:"email" json:"email"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Status      string    `db:"status" json:"status"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type UserSession struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	OrgID       uuid.UUID  `db:"org_id" json:"org_id"`
	UserID      uuid.UUID  `db:"user_id" json:"user_id"`
	TokenPrefix string     `db:"token_prefix" json:"token_prefix"`
	TokenHash   string     `db:"token_hash" json:"token_hash"`
	Status      string     `db:"status" json:"status"`
	ExpiresAt   time.Time  `db:"expires_at" json:"expires_at"`
	LastUsedAt  *time.Time `db:"last_used_at" json:"last_used_at"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at"`
	RevokedAt   *time.Time `db:"revoked_at" json:"revoked_at"`
}
