// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_pricing_versions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createModelPricingVersion = `-- name: CreateModelPricingVersion :one
INSERT INTO model_pricing_versions (
  id,
  org_id,
  model_id,
  version,
  input_price_micro_usd_per_1k_tokens,
  output_price_micro_usd_per_1k_tokens,
  status,
  effective_from,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, org_id, model_id, version, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, status, effective_from, effective_to, created_at
`

type CreateModelPricingVersionParams struct {
	ID                             uuid.UUID `db:"id" json:"id"`
	OrgID                          uuid.UUID `db:"org_id" json:"org_id"`
	ModelID                        uuid.UUID `db:"model_id" json:"model_id"`
	Version                        int32     `db:"version" json:"version"`
	InputPriceMicroUsdPer1kTokens  int64     `db:"input_price_micro_usd_per_1k_tokens" json:"input_price_micro_usd_per_1k_tokens"`
	OutputPriceMicroUsdPer1kTokens int64     `db:"output_price_micro_usd_per_1k_tokens" json:"output_price_micro_usd_per_1k_tokens"`
	Status                         string    `db:"status" json:"status"`
	EffectiveFrom                  time.Time `db:"effective_from" json:"effective_from"`
	CreatedAt                      time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateModelPricingVersion(ctx context.Context, arg CreateModelPricingVersionParams) (ModelPricingVersion, error) {
	row := q.db.QueryRow(ctx, createModelPricingVersion,
		arg.ID,
		arg.OrgID,
		arg.ModelID,
		arg.Version,
		arg.InputPriceMicroUsdPer1kTokens,
		arg.OutputPriceMicroUsdPer1kTokens,
		arg.Status,
		arg.EffectiveFrom,
		arg.CreatedAt,
	)
	var i ModelPricingVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelID,
		&i.Version,
		&i.InputPriceMicroUsdPer1kTokens,
		&i.OutputPriceMicroUsdPer1kTokens,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveModelPricingVersion = `-- name: GetActiveModelPricingVersion :one
SELECT id, org_id, model_id, version, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, status, effective_from, effective_to, created_at
FROM model_pricing_versions
WHERE org_id = $1 AND model_id = $2 AND status = 'active'
`

type GetActiveModelPricingVersionParams struct {
	OrgID   uuid.UUID `db:"org_id" json:"org_id"`
	ModelID uuid.UUID `db:"model_id" json:"model_id"`
}

func (q *Queries) GetActiveModelPricingVersion(ctx context.Context, arg GetActiveModelPricingVersionParams) (ModelPricingVersion, error) {
	row := q.db.QueryRow(ctx, getActiveModelPricingVersion, arg.OrgID, arg.ModelID)
	var i ModelPricingVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelID,
		&i.Version,
		&i.InputPriceMicroUsdPer1kTokens,
		&i.OutputPriceMicroUsdPer1kTokens,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getNextModelPricingVersionNumber = `-- name: GetNextModelPricingVersionNumber :one
SELECT COALESCE(MAX(version), 0)::integer + 1 AS next_version
FROM model_pricing_versions
WHERE org_id = $1 AND model_id = $2
`

type GetNextModelPricingVersionNumberParams struct {
	OrgID   uuid.UUID `db:"org_id" json:"org_id"`
	ModelID uuid.UUID `db:"model_id" json:"model_id"`
}

func (q *Queries) GetNextModelPricingVersionNumber(ctx context.Context, arg GetNextModelPricingVersionNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextModelPricingVersionNumber, arg.OrgID, arg.ModelID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const listModelPricingVersions = `-- name: ListModelPricingVersions :many
SELECT id, org_id, model_id, version, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, status, effective_from, effective_to, created_at
FROM model_pricing_versions
WHERE org_id = $1 AND model_id = $2
ORDER BY version DESC
`

type ListModelPricingVersionsParams struct {
	OrgID   uuid.UUID `db:"org_id" json:"org_id"`
	ModelID uuid.UUID `db:"model_id" json:"model_id"`
}

func (q *Queries) ListModelPricingVersions(ctx context.Context, arg ListModelPricingVersionsParams) ([]ModelPricingVersion, error) {
	rows, err := q.db.Query(ctx, listModelPricingVersions, arg.OrgID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPricingVersion{}
	for rows.Next() {
		var i ModelPricingVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ModelID,
			&i.Version,
			&i.InputPriceMicroUsdPer1kTokens,
			&i.OutputPriceMicroUsdPer1kTokens,
			&i.Status,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeActiveModelPricingVersion = `-- name: SupersedeActiveModelPricingVersion :one
UPDATE model_pricing_versions
SET status = 'superseded',
    effective_to = $3
WHERE org_id = $1 AND model_id = $2 AND status = 'active'
RETURNING id, org_id, model_id, version, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, status, effective_from, effective_to, created_at
`

type SupersedeActiveModelPricingVersionParams struct {
	OrgID       uuid.UUID  `db:"org_id" json:"org_id"`
	ModelID     uuid.UUID  `db:"model_id" json:"model_id"`
	EffectiveTo *time.Time `db:"effective_to" json:"effective_to"`
}

func (q *Queries) SupersedeActiveModelPricingVersion(ctx context.Context, arg SupersedeActiveModelPricingVersionParams) (ModelPricingVersion, error) {
	row := q.db.QueryRow(ctx, supersedeActiveModelPricingVersion, arg.OrgID, arg.ModelID, arg.EffectiveTo)
	var i ModelPricingVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ModelID,
		&i.Version,
		&i.InputPriceMicroUsdPer1kTokens,
		&i.OutputPriceMicroUsdPer1kTokens,
		&i.Status,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}
