// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModel = `-- name: CreateModel :one
INSERT INTO models (
  id,
  org_id,
  provider_id,
  provider_model_name,
  display_name,
  input_price_micro_usd_per_1k_tokens,
  output_price_micro_usd_per_1k_tokens,
  context_window,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, org_id, provider_id, provider_model_name, display_name, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, context_window, status, created_at, updated_at
`

type CreateModelParams struct {
	ID                             uuid.UUID   `db:"id" json:"id"`
	OrgID                          uuid.UUID   `db:"org_id" json:"org_id"`
	ProviderID                     uuid.UUID   `db:"provider_id" json:"provider_id"`
	ProviderModelName              string      `db:"provider_model_name" json:"provider_model_name"`
	DisplayName                    string      `db:"display_name" json:"display_name"`
	InputPriceMicroUsdPer1kTokens  int64       `db:"input_price_micro_usd_per_1k_tokens" json:"input_price_micro_usd_per_1k_tokens"`
	OutputPriceMicroUsdPer1kTokens int64       `db:"output_price_micro_usd_per_1k_tokens" json:"output_price_micro_usd_per_1k_tokens"`
	ContextWindow                  pgtype.Int4 `db:"context_window" json:"context_window"`
	Status                         string      `db:"status" json:"status"`
	CreatedAt                      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt                      time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.ID,
		arg.OrgID,
		arg.ProviderID,
		arg.ProviderModelName,
		arg.DisplayName,
		arg.InputPriceMicroUsdPer1kTokens,
		arg.OutputPriceMicroUsdPer1kTokens,
		arg.ContextWindow,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderID,
		&i.ProviderModelName,
		&i.DisplayName,
		&i.InputPriceMicroUsdPer1kTokens,
		&i.OutputPriceMicroUsdPer1kTokens,
		&i.ContextWindow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT id, org_id, provider_id, provider_model_name, display_name, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, context_window, status, created_at, updated_at
FROM models
WHERE org_id = $1 AND id = $2
`

type GetModelParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetModel(ctx context.Context, arg GetModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, arg.OrgID, arg.ID)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderID,
		&i.ProviderModelName,
		&i.DisplayName,
		&i.InputPriceMicroUsdPer1kTokens,
		&i.OutputPriceMicroUsdPer1kTokens,
		&i.ContextWindow,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, org_id, provider_id, provider_model_name, display_name, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, context_window, status, created_at, updated_at
FROM models
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListModels(ctx context.Context, orgID uuid.UUID) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProviderID,
			&i.ProviderModelName,
			&i.DisplayName,
			&i.InputPriceMicroUsdPer1kTokens,
			&i.OutputPriceMicroUsdPer1kTokens,
			&i.ContextWindow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByProvider = `-- name: ListModelsByProvider :many
SELECT id, org_id, provider_id, provider_model_name, display_name, input_price_micro_usd_per_1k_tokens, output_price_micro_usd_per_1k_tokens, context_window, status, created_at, updated_at
FROM models
WHERE org_id = $1 AND provider_id = $2
ORDER BY created_at DESC, id DESC
`

type ListModelsByProviderParams struct {
	OrgID      uuid.UUID `db:"org_id" json:"org_id"`
	ProviderID uuid.UUID `db:"provider_id" json:"provider_id"`
}

func (q *Queries) ListModelsByProvider(ctx context.Context, arg ListModelsByProviderParams) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModelsByProvider, arg.OrgID, arg.ProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProviderID,
			&i.ProviderModelName,
			&i.DisplayName,
			&i.InputPriceMicroUsdPer1kTokens,
			&i.OutputPriceMicroUsdPer1kTokens,
			&i.ContextWindow,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
