// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
  id,
  org_id,
  name,
  type,
  base_url,
  timeout_ms,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, org_id, name, type, base_url, timeout_ms, status, created_at, updated_at, last_health_status, last_health_checked_at, last_error_code, last_error_message
`

type CreateProviderParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	OrgID     uuid.UUID   `db:"org_id" json:"org_id"`
	Name      string      `db:"name" json:"name"`
	Type      string      `db:"type" json:"type"`
	BaseUrl   pgtype.Text `db:"base_url" json:"base_url"`
	TimeoutMs int32       `db:"timeout_ms" json:"timeout_ms"`
	Status    string      `db:"status" json:"status"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.TimeoutMs,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.TimeoutMs,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHealthStatus,
		&i.LastHealthCheckedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, org_id, name, type, base_url, timeout_ms, status, created_at, updated_at, last_health_status, last_health_checked_at, last_error_code, last_error_message
FROM providers
WHERE org_id = $1 AND id = $2
`

type GetProviderParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetProvider(ctx context.Context, arg GetProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, arg.OrgID, arg.ID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.TimeoutMs,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHealthStatus,
		&i.LastHealthCheckedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, org_id, name, type, base_url, timeout_ms, status, created_at, updated_at, last_health_status, last_health_checked_at, last_error_code, last_error_message
FROM providers
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProviders(ctx context.Context, orgID uuid.UUID) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.TimeoutMs,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastHealthStatus,
			&i.LastHealthCheckedAt,
			&i.LastErrorCode,
			&i.LastErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderHealth = `-- name: UpdateProviderHealth :one
UPDATE providers
SET
  last_health_status = $3,
  last_health_checked_at = $4,
  last_error_code = $5,
  last_error_message = $6,
  updated_at = $7
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, type, base_url, timeout_ms, status, created_at, updated_at, last_health_status, last_health_checked_at, last_error_code, last_error_message
`

type UpdateProviderHealthParams struct {
	OrgID               uuid.UUID   `db:"org_id" json:"org_id"`
	ID                  uuid.UUID   `db:"id" json:"id"`
	LastHealthStatus    pgtype.Text `db:"last_health_status" json:"last_health_status"`
	LastHealthCheckedAt *time.Time  `db:"last_health_checked_at" json:"last_health_checked_at"`
	LastErrorCode       pgtype.Text `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage    pgtype.Text `db:"last_error_message" json:"last_error_message"`
	UpdatedAt           time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateProviderHealth(ctx context.Context, arg UpdateProviderHealthParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderHealth,
		arg.OrgID,
		arg.ID,
		arg.LastHealthStatus,
		arg.LastHealthCheckedAt,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.TimeoutMs,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHealthStatus,
		&i.LastHealthCheckedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
	)
	return i, err
}
