// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_stats.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const providerModelLatencyStats = `-- name: ProviderModelLatencyStats :many
SELECT
  provider_id,
  model_id,
  count(*)::bigint AS request_count,
  COALESCE(percentile_cont(0.50) WITHIN GROUP (ORDER BY latency_ms), 0)::double precision AS p50_latency_ms,
  COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY latency_ms), 0)::double precision AS p95_latency_ms
FROM request_logs
WHERE org_id = $1
  AND completed_at >= $2
  AND completed_at < $3
  AND provider_id IS NOT NULL
  AND model_id IS NOT NULL
  AND status IN ('success', 'budget_warned')
GROUP BY provider_id, model_id
`

type ProviderModelLatencyStatsParams struct {
	OrgID         uuid.UUID `db:"org_id" json:"org_id"`
	CompletedAt   time.Time `db:"completed_at" json:"completed_at"`
	CompletedAt_2 time.Time `db:"completed_at_2" json:"completed_at_2"`
}

type ProviderModelLatencyStatsRow struct {
	ProviderID   *uuid.UUID `db:"provider_id" json:"provider_id"`
	ModelID      *uuid.UUID `db:"model_id" json:"model_id"`
	RequestCount int64      `db:"request_count" json:"request_count"`
	P50LatencyMs float64    `db:"p50_latency_ms" json:"p50_latency_ms"`
	P95LatencyMs float64    `db:"p95_latency_ms" json:"p95_latency_ms"`
}

func (q *Queries) ProviderModelLatencyStats(ctx context.Context, arg ProviderModelLatencyStatsParams) ([]ProviderModelLatencyStatsRow, error) {
	rows, err := q.db.Query(ctx, providerModelLatencyStats, arg.OrgID, arg.CompletedAt, arg.CompletedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderModelLatencyStatsRow{}
	for rows.Next() {
		var i ProviderModelLatencyStatsRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ModelID,
			&i.RequestCount,
			&i.P50LatencyMs,
			&i.P95LatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
