// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_secrets.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProviderSecret = `-- name: GetProviderSecret :one
SELECT id, org_id, provider_id, encrypted_api_key, nonce, key_version, created_at, updated_at
FROM provider_secrets
WHERE org_id = $1 AND provider_id = $2
`

type GetProviderSecretParams struct {
	OrgID      uuid.UUID `db:"org_id" json:"org_id"`
	ProviderID uuid.UUID `db:"provider_id" json:"provider_id"`
}

func (q *Queries) GetProviderSecret(ctx context.Context, arg GetProviderSecretParams) (ProviderSecret, error) {
	row := q.db.QueryRow(ctx, getProviderSecret, arg.OrgID, arg.ProviderID)
	var i ProviderSecret
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderID,
		&i.EncryptedApiKey,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProviderSecret = `-- name: UpsertProviderSecret :one
INSERT INTO provider_secrets (
  id,
  org_id,
  provider_id,
  encrypted_api_key,
  nonce,
  key_version,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (org_id, provider_id)
DO UPDATE SET
  encrypted_api_key = EXCLUDED.encrypted_api_key,
  nonce = EXCLUDED.nonce,
  key_version = EXCLUDED.key_version,
  updated_at = EXCLUDED.updated_at
RETURNING id, org_id, provider_id, encrypted_api_key, nonce, key_version, created_at, updated_at
`

type UpsertProviderSecretParams struct {
	ID              uuid.UUID `db:"id" json:"id"`
	OrgID           uuid.UUID `db:"org_id" json:"org_id"`
	ProviderID      uuid.UUID `db:"provider_id" json:"provider_id"`
	EncryptedApiKey string    `db:"encrypted_api_key" json:"encrypted_api_key"`
	Nonce           string    `db:"nonce" json:"nonce"`
	KeyVersion      int32     `db:"key_version" json:"key_version"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertProviderSecret(ctx context.Context, arg UpsertProviderSecretParams) (ProviderSecret, error) {
	row := q.db.QueryRow(ctx, upsertProviderSecret,
		arg.ID,
		arg.OrgID,
		arg.ProviderID,
		arg.EncryptedApiKey,
		arg.Nonce,
		arg.KeyVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProviderSecret
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProviderID,
		&i.EncryptedApiKey,
		&i.Nonce,
		&i.KeyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
