// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
  id,
  org_id,
  user_id,
  token_prefix,
  token_hash,
  status,
  expires_at,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, user_id, token_prefix, token_hash, status, expires_at, last_used_at, created_at, revoked_at
`

type CreateUserSessionParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	TokenPrefix string    `db:"token_prefix" json:"token_prefix"`
	TokenHash   string    `db:"token_hash" json:"token_hash"`
	Status      string    `db:"status" json:"status"`
	ExpiresAt   time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.TokenPrefix,
		arg.TokenHash,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveMembershipByOrgSlugAndEmail = `-- name: GetActiveMembershipByOrgSlugAndEmail :one
SELECT
  o.id AS org_id,
  o.slug AS org_slug,
  u.id AS user_id,
  u.email,
  u.display_name,
  m.id AS membership_id,
  m.role
FROM organizations o
JOIN org_memberships m ON m.org_id = o.id
JOIN users u ON u.id = m.user_id
WHERE o.slug = $1::text
  AND lower(u.email) = lower($2::text)
  AND o.status = 'active'
  AND u.status = 'active'
  AND m.status = 'active'
`

type GetActiveMembershipByOrgSlugAndEmailParams struct {
	OrgSlug string `db:"org_slug" json:"org_slug"`
	Email   string `db:"email" json:"email"`
}

type GetActiveMembershipByOrgSlugAndEmailRow struct {
	OrgID        uuid.UUID `db:"org_id" json:"org_id"`
	OrgSlug      string    `db:"org_slug" json:"org_slug"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	Email        string    `db:"email" json:"email"`
	DisplayName  string    `db:"display_name" json:"display_name"`
	MembershipID uuid.UUID `db:"membership_id" json:"membership_id"`
	Role         string    `db:"role" json:"role"`
}

func (q *Queries) GetActiveMembershipByOrgSlugAndEmail(ctx context.Context, arg GetActiveMembershipByOrgSlugAndEmailParams) (GetActiveMembershipByOrgSlugAndEmailRow, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByOrgSlugAndEmail, arg.OrgSlug, arg.Email)
	var i GetActiveMembershipByOrgSlugAndEmailRow
	err := row.Scan(
		&i.OrgID,
		&i.OrgSlug,
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.MembershipID,
		&i.Role,
	)
	return i, err
}

const getMembershipByOrgAndUser = `-- name: GetMembershipByOrgAndUser :one
SELECT id, org_id, user_id, role, status, created_at, updated_at
FROM org_memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipByOrgAndUserParams struct {
	OrgID  uuid.UUID `db:"org_id" json:"org_id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetMembershipByOrgAndUser(ctx context.Context, arg GetMembershipByOrgAndUserParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByOrgAndUser, arg.OrgID, arg.UserID)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, status, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByHash = `-- name: GetUserSessionByHash :one
SELECT
  s.id,
  s.org_id,
  s.user_id,
  s.token_prefix,
  s.token_hash,
  s.status,
  s.expires_at,
  s.last_used_at,
  s.created_at,
  s.revoked_at,
  m.id AS membership_id,
  m.role AS membership_role,
  m.status AS membership_status,
  u.email AS user_email,
  u.display_name AS user_display_name,
  u.status AS user_status
FROM user_sessions s
JOIN org_memberships m
  ON m.org_id = s.org_id
 AND m.user_id = s.user_id
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetUserSessionByHashRow struct {
	ID               uuid.UUID  `db:"id" json:"id"`
	OrgID            uuid.UUID  `db:"org_id" json:"org_id"`
	UserID           uuid.UUID  `db:"user_id" json:"user_id"`
	TokenPrefix      string     `db:"token_prefix" json:"token_prefix"`
	TokenHash        string     `db:"token_hash" json:"token_hash"`
	Status           string     `db:"status" json:"status"`
	ExpiresAt        time.Time  `db:"expires_at" json:"expires_at"`
	LastUsedAt       *time.Time `db:"last_used_at" json:"last_used_at"`
	CreatedAt        time.Time  `db:"created_at" json:"created_at"`
	RevokedAt        *time.Time `db:"revoked_at" json:"revoked_at"`
	MembershipID     uuid.UUID  `db:"membership_id" json:"membership_id"`
	MembershipRole   string     `db:"membership_role" json:"membership_role"`
	MembershipStatus string     `db:"membership_status" json:"membership_status"`
	UserEmail        string     `db:"user_email" json:"user_email"`
	UserDisplayName  string     `db:"user_display_name" json:"user_display_name"`
	UserStatus       string     `db:"user_status" json:"user_status"`
}

func (q *Queries) GetUserSessionByHash(ctx context.Context, tokenHash string) (GetUserSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, getUserSessionByHash, tokenHash)
	var i GetUserSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.MembershipID,
		&i.MembershipRole,
		&i.MembershipStatus,
		&i.UserEmail,
		&i.UserDisplayName,
		&i.UserStatus,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT
  m.id AS membership_id,
  m.org_id,
  m.user_id,
  u.email,
  u.display_name,
  m.role,
  m.status,
  m.created_at,
  m.updated_at
FROM org_memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.created_at DESC, m.id DESC
`

type ListOrgMembersRow struct {
	MembershipID uuid.UUID `db:"membership_id" json:"membership_id"`
	OrgID        uuid.UUID `db:"org_id" json:"org_id"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	Email        string    `db:"email" json:"email"`
	DisplayName  string    `db:"display_name" json:"display_name"`
	Role         string    `db:"role" json:"role"`
	Status       string    `db:"status" json:"status"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.OrgID,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserSession = `-- name: RevokeUserSession :one
UPDATE user_sessions
SET status = 'revoked',
    revoked_at = $3
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, user_id, token_prefix, token_hash, status, expires_at, last_used_at, created_at, revoked_at
`

type RevokeUserSessionParams struct {
	OrgID     uuid.UUID  `db:"org_id" json:"org_id"`
	ID        uuid.UUID  `db:"id" json:"id"`
	RevokedAt *time.Time `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, revokeUserSession, arg.OrgID, arg.ID, arg.RevokedAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.TokenPrefix,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchUserSessionLastUsed = `-- name: TouchUserSessionLastUsed :exec
UPDATE user_sessions
SET last_used_at = $3
WHERE org_id = $1 AND id = $2
`

type TouchUserSessionLastUsedParams struct {
	OrgID      uuid.UUID  `db:"org_id" json:"org_id"`
	ID         uuid.UUID  `db:"id" json:"id"`
	LastUsedAt *time.Time `db:"last_used_at" json:"last_used_at"`
}

func (q *Queries) TouchUserSessionLastUsed(ctx context.Context, arg TouchUserSessionLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchUserSessionLastUsed, arg.OrgID, arg.ID, arg.LastUsedAt)
	return err
}

const upsertOrgMembership = `-- name: UpsertOrgMembership :one
INSERT INTO org_memberships (
  id,
  org_id,
  user_id,
  role,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (org_id, user_id)
DO UPDATE SET
  role = EXCLUDED.role,
  status = EXCLUDED.status,
  updated_at = EXCLUDED.updated_at
RETURNING id, org_id, user_id, role, status, created_at, updated_at
`

type UpsertOrgMembershipParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	OrgID     uuid.UUID `db:"org_id" json:"org_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Role      string    `db:"role" json:"role"`
	Status    string    `db:"status" json:"status"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertOrgMembership(ctx context.Context, arg UpsertOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, upsertOrgMembership,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (
  id,
  email,
  display_name,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (email)
DO UPDATE SET
  display_name = EXCLUDED.display_name,
  updated_at = EXCLUDED.updated_at
RETURNING id, email, display_name, status, created_at, updated_at
`

type UpsertUserByEmailParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Email       string    `db:"email" json:"email"`
	DisplayName string    `db:"display_name" json:"display_name"`
	Status      string    `db:"status" json:"status"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
