// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_logs.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertRequestLog = `-- name: InsertRequestLog :one
INSERT INTO request_logs (
  id,
  org_id,
  api_key_id,
  provider_id,
  model_id,
  route_policy_id,
  method,
  path,
  request_model,
  status,
  status_code,
  error_code,
  request_hash,
  response_hash,
  latency_ms,
  provider_latency_ms,
  metadata,
  started_at,
  completed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19
) RETURNING id, org_id, api_key_id, provider_id, model_id, route_policy_id, method, path, request_model, status, status_code, error_code, request_hash, response_hash, latency_ms, provider_latency_ms, metadata, started_at, completed_at
`

type InsertRequestLogParams struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	OrgID             uuid.UUID        `db:"org_id" json:"org_id"`
	ApiKeyID          *uuid.UUID       `db:"api_key_id" json:"api_key_id"`
	ProviderID        *uuid.UUID       `db:"provider_id" json:"provider_id"`
	ModelID           *uuid.UUID       `db:"model_id" json:"model_id"`
	RoutePolicyID     *uuid.UUID       `db:"route_policy_id" json:"route_policy_id"`
	Method            string           `db:"method" json:"method"`
	Path              string           `db:"path" json:"path"`
	RequestModel      pgtype.Text      `db:"request_model" json:"request_model"`
	Status            string           `db:"status" json:"status"`
	StatusCode        int32            `db:"status_code" json:"status_code"`
	ErrorCode         pgtype.Text      `db:"error_code" json:"error_code"`
	RequestHash       pgtype.Text      `db:"request_hash" json:"request_hash"`
	ResponseHash      pgtype.Text      `db:"response_hash" json:"response_hash"`
	LatencyMs         int32            `db:"latency_ms" json:"latency_ms"`
	ProviderLatencyMs pgtype.Int4      `db:"provider_latency_ms" json:"provider_latency_ms"`
	Metadata          *json.RawMessage `db:"metadata" json:"metadata"`
	StartedAt         time.Time        `db:"started_at" json:"started_at"`
	CompletedAt       time.Time        `db:"completed_at" json:"completed_at"`
}

func (q *Queries) InsertRequestLog(ctx context.Context, arg InsertRequestLogParams) (RequestLog, error) {
	row := q.db.QueryRow(ctx, insertRequestLog,
		arg.ID,
		arg.OrgID,
		arg.ApiKeyID,
		arg.ProviderID,
		arg.ModelID,
		arg.RoutePolicyID,
		arg.Method,
		arg.Path,
		arg.RequestModel,
		arg.Status,
		arg.StatusCode,
		arg.ErrorCode,
		arg.RequestHash,
		arg.ResponseHash,
		arg.LatencyMs,
		arg.ProviderLatencyMs,
		arg.Metadata,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i RequestLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ApiKeyID,
		&i.ProviderID,
		&i.ModelID,
		&i.RoutePolicyID,
		&i.Method,
		&i.Path,
		&i.RequestModel,
		&i.Status,
		&i.StatusCode,
		&i.ErrorCode,
		&i.RequestHash,
		&i.ResponseHash,
		&i.LatencyMs,
		&i.ProviderLatencyMs,
		&i.Metadata,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listRequestLogs = `-- name: ListRequestLogs :many
SELECT id, org_id, api_key_id, provider_id, model_id, route_policy_id, method, path, request_model, status, status_code, error_code, request_hash, response_hash, latency_ms, provider_latency_ms, metadata, started_at, completed_at
FROM request_logs
WHERE org_id = $1
  AND started_at >= $2
  AND started_at < $3
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::uuid IS NULL OR api_key_id = $5::uuid)
  AND ($6::uuid IS NULL OR provider_id = $6::uuid)
  AND ($7::uuid IS NULL OR model_id = $7::uuid)
ORDER BY started_at DESC, id DESC
LIMIT $9
OFFSET $8
`

type ListRequestLogsParams struct {
	OrgID      uuid.UUID   `db:"org_id" json:"org_id"`
	FromAt     time.Time   `db:"from_at" json:"from_at"`
	ToAt       time.Time   `db:"to_at" json:"to_at"`
	Status     pgtype.Text `db:"status" json:"status"`
	ApiKeyID   *uuid.UUID  `db:"api_key_id" json:"api_key_id"`
	ProviderID *uuid.UUID  `db:"provider_id" json:"provider_id"`
	ModelID    *uuid.UUID  `db:"model_id" json:"model_id"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListRequestLogs(ctx context.Context, arg ListRequestLogsParams) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, listRequestLogs,
		arg.OrgID,
		arg.FromAt,
		arg.ToAt,
		arg.Status,
		arg.ApiKeyID,
		arg.ProviderID,
		arg.ModelID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestLog{}
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ApiKeyID,
			&i.ProviderID,
			&i.ModelID,
			&i.RoutePolicyID,
			&i.Method,
			&i.Path,
			&i.RequestModel,
			&i.Status,
			&i.StatusCode,
			&i.ErrorCode,
			&i.RequestHash,
			&i.ResponseHash,
			&i.LatencyMs,
			&i.ProviderLatencyMs,
			&i.Metadata,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
