// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: route_policies.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoutePolicy = `-- name: CreateRoutePolicy :one
INSERT INTO route_policies (
  id,
  org_id,
  name,
  match_model,
  strategy,
  status,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, name, match_model, strategy, status, created_at, updated_at
`

type CreateRoutePolicyParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	OrgID      uuid.UUID `db:"org_id" json:"org_id"`
	Name       string    `db:"name" json:"name"`
	MatchModel string    `db:"match_model" json:"match_model"`
	Strategy   string    `db:"strategy" json:"strategy"`
	Status     string    `db:"status" json:"status"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateRoutePolicy(ctx context.Context, arg CreateRoutePolicyParams) (RoutePolicy, error) {
	row := q.db.QueryRow(ctx, createRoutePolicy,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.MatchModel,
		arg.Strategy,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RoutePolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.MatchModel,
		&i.Strategy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRouteTarget = `-- name: CreateRouteTarget :one
INSERT INTO route_targets (
  id,
  org_id,
  route_policy_id,
  provider_id,
  model_id,
  priority,
  weight,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, route_policy_id, provider_id, model_id, priority, weight, created_at
`

type CreateRouteTargetParams struct {
	ID            uuid.UUID `db:"id" json:"id"`
	OrgID         uuid.UUID `db:"org_id" json:"org_id"`
	RoutePolicyID uuid.UUID `db:"route_policy_id" json:"route_policy_id"`
	ProviderID    uuid.UUID `db:"provider_id" json:"provider_id"`
	ModelID       uuid.UUID `db:"model_id" json:"model_id"`
	Priority      int32     `db:"priority" json:"priority"`
	Weight        int32     `db:"weight" json:"weight"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateRouteTarget(ctx context.Context, arg CreateRouteTargetParams) (RouteTarget, error) {
	row := q.db.QueryRow(ctx, createRouteTarget,
		arg.ID,
		arg.OrgID,
		arg.RoutePolicyID,
		arg.ProviderID,
		arg.ModelID,
		arg.Priority,
		arg.Weight,
		arg.CreatedAt,
	)
	var i RouteTarget
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.RoutePolicyID,
		&i.ProviderID,
		&i.ModelID,
		&i.Priority,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const getRoutePolicy = `-- name: GetRoutePolicy :one
SELECT id, org_id, name, match_model, strategy, status, created_at, updated_at
FROM route_policies
WHERE org_id = $1 AND id = $2
`

type GetRoutePolicyParams struct {
	OrgID uuid.UUID `db:"org_id" json:"org_id"`
	ID    uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) GetRoutePolicy(ctx context.Context, arg GetRoutePolicyParams) (RoutePolicy, error) {
	row := q.db.QueryRow(ctx, getRoutePolicy, arg.OrgID, arg.ID)
	var i RoutePolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.MatchModel,
		&i.Strategy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoutePolicyByMatchModel = `-- name: GetRoutePolicyByMatchModel :one
SELECT id, org_id, name, match_model, strategy, status, created_at, updated_at
FROM route_policies
WHERE org_id = $1 AND match_model = $2 AND status = 'active'
`

type GetRoutePolicyByMatchModelParams struct {
	OrgID      uuid.UUID `db:"org_id" json:"org_id"`
	MatchModel string    `db:"match_model" json:"match_model"`
}

func (q *Queries) GetRoutePolicyByMatchModel(ctx context.Context, arg GetRoutePolicyByMatchModelParams) (RoutePolicy, error) {
	row := q.db.QueryRow(ctx, getRoutePolicyByMatchModel, arg.OrgID, arg.MatchModel)
	var i RoutePolicy
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.MatchModel,
		&i.Strategy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoutePolicies = `-- name: ListRoutePolicies :many
SELECT id, org_id, name, match_model, strategy, status, created_at, updated_at
FROM route_policies
WHERE org_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListRoutePolicies(ctx context.Context, orgID uuid.UUID) ([]RoutePolicy, error) {
	rows, err := q.db.Query(ctx, listRoutePolicies, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoutePolicy{}
	for rows.Next() {
		var i RoutePolicy
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.MatchModel,
			&i.Strategy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRouteTargets = `-- name: ListRouteTargets :many
SELECT id, org_id, route_policy_id, provider_id, model_id, priority, weight, created_at
FROM route_targets
WHERE org_id = $1 AND route_policy_id = $2
ORDER BY priority ASC, id ASC
`

type ListRouteTargetsParams struct {
	OrgID         uuid.UUID `db:"org_id" json:"org_id"`
	RoutePolicyID uuid.UUID `db:"route_policy_id" json:"route_policy_id"`
}

func (q *Queries) ListRouteTargets(ctx context.Context, arg ListRouteTargetsParams) ([]RouteTarget, error) {
	rows, err := q.db.Query(ctx, listRouteTargets, arg.OrgID, arg.RoutePolicyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RouteTarget{}
	for rows.Next() {
		var i RouteTarget
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.RoutePolicyID,
			&i.ProviderID,
			&i.ModelID,
			&i.Priority,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
