// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const insertCostRecord = `-- name: InsertCostRecord :one
INSERT INTO cost_records (
  id,
  usage_record_id,
  org_id,
  provider_id,
  model_id,
  currency,
  input_cost_micro,
  output_cost_micro,
  total_cost_micro,
  pricing_version_id,
  pricing_snapshot,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, usage_record_id, org_id, provider_id, model_id, currency, input_cost_micro, output_cost_micro, total_cost_micro, pricing_snapshot, created_at, pricing_version_id
`

type InsertCostRecordParams struct {
	ID               uuid.UUID       `db:"id" json:"id"`
	UsageRecordID    uuid.UUID       `db:"usage_record_id" json:"usage_record_id"`
	OrgID            uuid.UUID       `db:"org_id" json:"org_id"`
	ProviderID       uuid.UUID       `db:"provider_id" json:"provider_id"`
	ModelID          uuid.UUID       `db:"model_id" json:"model_id"`
	Currency         string          `db:"currency" json:"currency"`
	InputCostMicro   int64           `db:"input_cost_micro" json:"input_cost_micro"`
	OutputCostMicro  int64           `db:"output_cost_micro" json:"output_cost_micro"`
	TotalCostMicro   int64           `db:"total_cost_micro" json:"total_cost_micro"`
	PricingVersionID *uuid.UUID      `db:"pricing_version_id" json:"pricing_version_id"`
	PricingSnapshot  json.RawMessage `db:"pricing_snapshot" json:"pricing_snapshot"`
	CreatedAt        time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertCostRecord(ctx context.Context, arg InsertCostRecordParams) (CostRecord, error) {
	row := q.db.QueryRow(ctx, insertCostRecord,
		arg.ID,
		arg.UsageRecordID,
		arg.OrgID,
		arg.ProviderID,
		arg.ModelID,
		arg.Currency,
		arg.InputCostMicro,
		arg.OutputCostMicro,
		arg.TotalCostMicro,
		arg.PricingVersionID,
		arg.PricingSnapshot,
		arg.CreatedAt,
	)
	var i CostRecord
	err := row.Scan(
		&i.ID,
		&i.UsageRecordID,
		&i.OrgID,
		&i.ProviderID,
		&i.ModelID,
		&i.Currency,
		&i.InputCostMicro,
		&i.OutputCostMicro,
		&i.TotalCostMicro,
		&i.PricingSnapshot,
		&i.CreatedAt,
		&i.PricingVersionID,
	)
	return i, err
}

const insertUsageRecord = `-- name: InsertUsageRecord :one
INSERT INTO usage_records (
  id,
  request_log_id,
  org_id,
  api_key_id,
  provider_id,
  model_id,
  prompt_tokens,
  completion_tokens,
  total_tokens,
  provider_usage_json,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, request_log_id, org_id, api_key_id, provider_id, model_id, prompt_tokens, completion_tokens, total_tokens, provider_usage_json, created_at
`

type InsertUsageRecordParams struct {
	ID                uuid.UUID        `db:"id" json:"id"`
	RequestLogID      uuid.UUID        `db:"request_log_id" json:"request_log_id"`
	OrgID             uuid.UUID        `db:"org_id" json:"org_id"`
	ApiKeyID          uuid.UUID        `db:"api_key_id" json:"api_key_id"`
	ProviderID        uuid.UUID        `db:"provider_id" json:"provider_id"`
	ModelID           uuid.UUID        `db:"model_id" json:"model_id"`
	PromptTokens      int32            `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens  int32            `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens       int32            `db:"total_tokens" json:"total_tokens"`
	ProviderUsageJson *json.RawMessage `db:"provider_usage_json" json:"provider_usage_json"`
	CreatedAt         time.Time        `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertUsageRecord(ctx context.Context, arg InsertUsageRecordParams) (UsageRecord, error) {
	row := q.db.QueryRow(ctx, insertUsageRecord,
		arg.ID,
		arg.RequestLogID,
		arg.OrgID,
		arg.ApiKeyID,
		arg.ProviderID,
		arg.ModelID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.ProviderUsageJson,
		arg.CreatedAt,
	)
	var i UsageRecord
	err := row.Scan(
		&i.ID,
		&i.RequestLogID,
		&i.OrgID,
		&i.ApiKeyID,
		&i.ProviderID,
		&i.ModelID,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.ProviderUsageJson,
		&i.CreatedAt,
	)
	return i, err
}

const usageSummaryByAPIKey = `-- name: UsageSummaryByAPIKey :many
SELECT
  ur.api_key_id,
  count(*)::bigint AS request_count,
  count(*) FILTER (WHERE rl.status IN ('success', 'budget_warned'))::bigint AS success_count,
  count(*) FILTER (WHERE rl.status NOT IN ('success', 'budget_warned'))::bigint AS error_count,
  COALESCE(sum(ur.prompt_tokens), 0)::bigint AS prompt_tokens,
  COALESCE(sum(ur.completion_tokens), 0)::bigint AS completion_tokens,
  COALESCE(sum(ur.total_tokens), 0)::bigint AS total_tokens,
  COALESCE(sum(cr.total_cost_micro), 0)::bigint AS total_cost_micro_usd,
  COALESCE(avg(rl.latency_ms), 0)::double precision AS avg_latency_ms
FROM usage_records ur
JOIN request_logs rl
  ON rl.org_id = ur.org_id
 AND rl.id = ur.request_log_id
LEFT JOIN cost_records cr
  ON cr.org_id = ur.org_id
 AND cr.usage_record_id = ur.id
WHERE ur.org_id = $1
  AND ur.created_at >= $2
  AND ur.created_at < $3
GROUP BY ur.api_key_id
ORDER BY total_cost_micro_usd DESC, request_count DESC
`

type UsageSummaryByAPIKeyParams struct {
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
}

type UsageSummaryByAPIKeyRow struct {
	ApiKeyID          uuid.UUID `db:"api_key_id" json:"api_key_id"`
	RequestCount      int64     `db:"request_count" json:"request_count"`
	SuccessCount      int64     `db:"success_count" json:"success_count"`
	ErrorCount        int64     `db:"error_count" json:"error_count"`
	PromptTokens      int64     `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens  int64     `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens       int64     `db:"total_tokens" json:"total_tokens"`
	TotalCostMicroUsd int64     `db:"total_cost_micro_usd" json:"total_cost_micro_usd"`
	AvgLatencyMs      float64   `db:"avg_latency_ms" json:"avg_latency_ms"`
}

func (q *Queries) UsageSummaryByAPIKey(ctx context.Context, arg UsageSummaryByAPIKeyParams) ([]UsageSummaryByAPIKeyRow, error) {
	rows, err := q.db.Query(ctx, usageSummaryByAPIKey, arg.OrgID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageSummaryByAPIKeyRow{}
	for rows.Next() {
		var i UsageSummaryByAPIKeyRow
		if err := rows.Scan(
			&i.ApiKeyID,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.TotalCostMicroUsd,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageSummaryByModel = `-- name: UsageSummaryByModel :many
SELECT
  ur.model_id,
  count(*)::bigint AS request_count,
  count(*) FILTER (WHERE rl.status IN ('success', 'budget_warned'))::bigint AS success_count,
  count(*) FILTER (WHERE rl.status NOT IN ('success', 'budget_warned'))::bigint AS error_count,
  COALESCE(sum(ur.prompt_tokens), 0)::bigint AS prompt_tokens,
  COALESCE(sum(ur.completion_tokens), 0)::bigint AS completion_tokens,
  COALESCE(sum(ur.total_tokens), 0)::bigint AS total_tokens,
  COALESCE(sum(cr.total_cost_micro), 0)::bigint AS total_cost_micro_usd,
  COALESCE(avg(rl.latency_ms), 0)::double precision AS avg_latency_ms
FROM usage_records ur
JOIN request_logs rl
  ON rl.org_id = ur.org_id
 AND rl.id = ur.request_log_id
LEFT JOIN cost_records cr
  ON cr.org_id = ur.org_id
 AND cr.usage_record_id = ur.id
WHERE ur.org_id = $1
  AND ur.created_at >= $2
  AND ur.created_at < $3
GROUP BY ur.model_id
ORDER BY total_cost_micro_usd DESC, request_count DESC
`

type UsageSummaryByModelParams struct {
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
}

type UsageSummaryByModelRow struct {
	ModelID           uuid.UUID `db:"model_id" json:"model_id"`
	RequestCount      int64     `db:"request_count" json:"request_count"`
	SuccessCount      int64     `db:"success_count" json:"success_count"`
	ErrorCount        int64     `db:"error_count" json:"error_count"`
	PromptTokens      int64     `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens  int64     `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens       int64     `db:"total_tokens" json:"total_tokens"`
	TotalCostMicroUsd int64     `db:"total_cost_micro_usd" json:"total_cost_micro_usd"`
	AvgLatencyMs      float64   `db:"avg_latency_ms" json:"avg_latency_ms"`
}

func (q *Queries) UsageSummaryByModel(ctx context.Context, arg UsageSummaryByModelParams) ([]UsageSummaryByModelRow, error) {
	rows, err := q.db.Query(ctx, usageSummaryByModel, arg.OrgID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageSummaryByModelRow{}
	for rows.Next() {
		var i UsageSummaryByModelRow
		if err := rows.Scan(
			&i.ModelID,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.TotalCostMicroUsd,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usageSummaryByProvider = `-- name: UsageSummaryByProvider :many
SELECT
  ur.provider_id,
  count(*)::bigint AS request_count,
  count(*) FILTER (WHERE rl.status IN ('success', 'budget_warned'))::bigint AS success_count,
  count(*) FILTER (WHERE rl.status NOT IN ('success', 'budget_warned'))::bigint AS error_count,
  COALESCE(sum(ur.prompt_tokens), 0)::bigint AS prompt_tokens,
  COALESCE(sum(ur.completion_tokens), 0)::bigint AS completion_tokens,
  COALESCE(sum(ur.total_tokens), 0)::bigint AS total_tokens,
  COALESCE(sum(cr.total_cost_micro), 0)::bigint AS total_cost_micro_usd,
  COALESCE(avg(rl.latency_ms), 0)::double precision AS avg_latency_ms
FROM usage_records ur
JOIN request_logs rl
  ON rl.org_id = ur.org_id
 AND rl.id = ur.request_log_id
LEFT JOIN cost_records cr
  ON cr.org_id = ur.org_id
 AND cr.usage_record_id = ur.id
WHERE ur.org_id = $1
  AND ur.created_at >= $2
  AND ur.created_at < $3
GROUP BY ur.provider_id
ORDER BY total_cost_micro_usd DESC, request_count DESC
`

type UsageSummaryByProviderParams struct {
	OrgID       uuid.UUID `db:"org_id" json:"org_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
}

type UsageSummaryByProviderRow struct {
	ProviderID        uuid.UUID `db:"provider_id" json:"provider_id"`
	RequestCount      int64     `db:"request_count" json:"request_count"`
	SuccessCount      int64     `db:"success_count" json:"success_count"`
	ErrorCount        int64     `db:"error_count" json:"error_count"`
	PromptTokens      int64     `db:"prompt_tokens" json:"prompt_tokens"`
	CompletionTokens  int64     `db:"completion_tokens" json:"completion_tokens"`
	TotalTokens       int64     `db:"total_tokens" json:"total_tokens"`
	TotalCostMicroUsd int64     `db:"total_cost_micro_usd" json:"total_cost_micro_usd"`
	AvgLatencyMs      float64   `db:"avg_latency_ms" json:"avg_latency_ms"`
}

func (q *Queries) UsageSummaryByProvider(ctx context.Context, arg UsageSummaryByProviderParams) ([]UsageSummaryByProviderRow, error) {
	rows, err := q.db.Query(ctx, usageSummaryByProvider, arg.OrgID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageSummaryByProviderRow{}
	for rows.Next() {
		var i UsageSummaryByProviderRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.RequestCount,
			&i.SuccessCount,
			&i.ErrorCount,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.TotalTokens,
			&i.TotalCostMicroUsd,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
